deployment:
  tasks:
    - export DEPLOYPATH=/home/sdinpre2/
    - /bin/cp -r * $DEPLOYPATH #copy all from root
#    - /bin/cp -r ./public/* $DEPLOYPATH/public_html/
    - /bin/cp ./public/js/*.js $DEPLOYPATH/public_html/pbpm/public/js
    - /bin/cp ./public/css/*.css $DEPLOYPATH/public_html/pbpm/public/css
